    $ echo Hello, World! Hello, World! ...
    $ nano hello. The first line of our script is called a shebang. ...
    $ chmod +x hello. Now we can actually run the script. ...
    $ ./hello Hello, World!
